// angular7/Spotiapp_/src/app/components/search/search.component.ts
import { Component } from '@angular/core';
import {SpotifyService} from '../../service/spotify.service';
@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styles: []
})
export class SearchComponent{

  artist: any[] = [];
  loading: boolean = false;
  constructor(private spotify: SpotifyService) { }

  buscar (termino: string){
    this.loading = true;
    this.spotify.getArtist(termino).subscribe((data: any) => {
      this.artist =  data;
      this.loading = false;
    });
  }

}

<app-loading *ngIf="loading"></app-loading>
<div class="row animated fadeIn m-5">
  <div class="col">
    <input type="text" #termino (keyup)="buscar(termino.value)" class="form-control" placeholder="Buscar artista">
  </div>

</div>
<app-tarjets *ngIf="!loading" [items]="artist"></app-tarjets>

// reactJS/store-app-reactjs/src/components/Search/Search.js
import React, {Component} from 'react';

class Search extends Component{
  readData = (e) => {
    this.props.search(e.target.value);
  }
  render(){
    return(
      <div className="row">
        <div className="col-md-12">
          <input input="text" className="form-control App-search" placeholder="Search form" onChange={this.readData}/>
        </div>
      </div>
    )
  }
}

export default Search;
